Hello Microverse Pull Request
PrantoshB/Hello-Microverse pull request #1
Opened 2022-10-25 18:19 UTC by PrantoshB

2022-10-25 18:55 UTC, TuyishimireEric requested changes
# Status: REQUEST CHANGES :recycle: 
## Hi @PrantoshB  :hand: :hand: 
I am @tuyishimireeric your reviewer for this PR :man_beard:

Great work so far! 👏
Thank you for implementing most of the project requirements good job! :heavy_check_mark: 
however, there are some issues that you still need to work on to go to the next project, but you are almost there!
![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)


## To highlight 🎯

:heavy_check_mark:  Gitflow used. :+1: 
:heavy_check_mark: No Linter errors :+1: 
:heavy_check_mark: Descriptive commit messages :+1: 
:heavy_check_mark: Descriptive README file :+1: 

## Required Changes ♻️

- [ ]  Kindly ensure your PR description is never empty. It should tell us about what feature you added and what effect it has on the project. It's usually best practice to have a list of bullet point of what you implemented in the PR. Kindly give a description in the section shown below
![image](https://user-images.githubusercontent.com/102757126/197857473-4a5496dc-8c11-486e-9f41-9aeef5a1a5ba.png)

## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 18:55 UTC, TuyishimireEric commented on README.md
> +Hello Microverse
- [ ] [OPTIONAL] Good job on adding a professional and descriptive README :clap: :clap:, 
what do think by making your project name ```#Hello Microverse``` as your main title and adding a short project description as it is on our README [template  ](https://github.com/microverseinc/readme-template)
![image](https://user-images.githubusercontent.com/102757126/197854996-0c8e1884-566d-4bd3-85cd-4f82bad60c45.png)

I think it will make your project more attractive :heart:

2022-10-26 05:51 UTC, PrantoshB commented on README.md
> +Hello Microverse
Thanks. I have added the PR description.

2022-10-26 05:59 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @PrantoshB 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- No Linter errors ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
- Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 05:59 UTC, Bondok6 commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [OPTIONAL] the MIT link is broken, so I suggest adding the `MIT.md` file to your project 👌, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it 😉

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯

- [OPTIONAL] Also, I suggest removing this `_NOTE ...` recommendation from your README file 👍

2022-10-26 06:01 UTC, merged